# Generated by Django 4.1.13 on 2024-06-02 03:15

import backend.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('namelastname', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('date_naissance', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('role', models.CharField(blank=True, max_length=1)),
                ('phone_number', models.IntegerField(blank=True, unique=True)),
                ('billing_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.IntegerField(blank=True)),
                ('cin', models.IntegerField(blank=True)),
                ('valid_paiement', models.BooleanField(default=False)),
                ('compte_valid', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('image_cin_recto', models.ImageField(null=True, upload_to=backend.models.upload_to)),
                ('image_cin_verso', models.ImageField(null=True, upload_to=backend.models.upload_to)),
                ('image_permi_recto', models.ImageField(null=True, upload_to=backend.models.upload_to)),
                ('image_permi_verso', models.ImageField(null=True, upload_to=backend.models.upload_to)),
                ('image_carte_grise_recto', models.ImageField(null=True, upload_to=backend.models.upload_to)),
                ('reçus_paiement', models.ImageField(null=True, upload_to=backend.models.upload_to)),
                ('image_carte_grise_verso', models.ImageField(null=True, upload_to=backend.models.upload_to)),
                ('profile_image', models.ImageField(null=True, upload_to=backend.models.upload_to)),
                ('matricule_vehicule', models.CharField(blank=True, max_length=500)),
                ('marque_vehicule', models.CharField(blank=True, max_length=500)),
                ('tonnage_vehicule', models.IntegerField(blank=True)),
                ('username', models.CharField(blank=True, max_length=150, unique=True)),
                ('is_calendrier_valid', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('destenaire_adresse', models.CharField(max_length=500)),
                ('destenaire_email', models.CharField(max_length=500)),
                ('destenaire_tel', models.IntegerField(blank=True)),
                ('destenaire_nom_pre', models.CharField(max_length=500)),
                ('destenaire_ville', models.CharField(max_length=500)),
                ('destenaire_Gouvernorat', models.CharField(max_length=500)),
                ('destenaire_zipcode', models.IntegerField(blank=True)),
                ('poid_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('list_article_json', models.TextField()),
                ('status_colis', models.CharField(max_length=500)),
                ('jour_depart', models.CharField(blank=True, max_length=500)),
                ('creation_date', models.CharField(blank=True, max_length=500)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis_client', to=settings.AUTH_USER_MODEL)),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis_transporteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransporteurCalendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_depart', models.CharField(blank=True, max_length=500, unique=True)),
                ('heure_depart', models.CharField(blank=True, max_length=500)),
                ('poids_disponible_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poids_total_colis_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destenaire_zipcode', models.IntegerField(blank=True)),
                ('destenaire_Gouvernorat', models.CharField(max_length=500)),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reclamation', models.CharField(blank=True, max_length=500)),
                ('sujet', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=900)),
                ('reponse', models.CharField(max_length=900)),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.colis')),
                ('defendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defendeur', to=settings.AUTH_USER_MODEL)),
                ('reclamant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
